### ISSUE TITLE
Current release of rulma does not include es/src files

### ISSUE THREAD

**Issue by kennetvu** [alexanbj/rulma#21]
![image](https://cloud.githubusercontent.com/assets/1459265/23866528/65a1487e-0819-11e7-948a-c10294374b6c.png)

Current release of rulma 0.0.1 does not include any files :(

**Comment by alexanbj** [comment]
I guess this is because the 0.0.1 version was published with Yarn https://github.com/yarnpkg/yarn/issues/2851

**Comment by alexanbj** [comment]
This is now fixed. The new version was published with NPM, so this is working now.
