### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by alexanbj** [alexanbj/rulma#6]
When #4 gets fixed, we should setup continuous integration. TravisCI maybe?

**Comment by kennetvu** [comment]
@alexanbj can you make me repo admin ? I want to add CircleCI and other CI tools :)

**Comment by alexanbj** [comment]
Boooh... Seems I can't grant you that kind of permission, since this is a user repository and not an organization repository :/

**Comment by alexanbj** [comment]
Fixed in #25
